name: Generate Snake

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # Ensure PowerShell is the shell being used
      - name: Set up PowerShell environment
        shell: powershell

      # Generates the snake
      - name: Generate the snake
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b output
          mkdir dist
          # Adjust the paths accordingly for Windows
          .\snk.ps1 -GitHubUsername pradeish29 -GifPath .\dist\github-contribution-grid-snake.gif -SvgPath .\dist\github-contribution-grid-snake.svg

      # Show the status of the build
      - name: Show Git status
        run: git status

      # Add, commit, and push the changes
      - name: Push changes
        run: |
          git add .
          git commit -m "Generate snake"
          git push origin output

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: output
          folder: dist
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
